#!/usr/bin/env python3
"""
etl_template.py — 数据管线模板
对标 onecargokit.com 的 etl_hs_data.py（数据文件头部注释 "Auto-generated by etl_hs_data.py"）

职责：从公开数据源抓取/解析 → 加工 → 生成 data/*.js 静态文件 → git commit 即完成"数据更新"

用法：
    python3 etl_template.py              # 跑全部管线
    python3 etl_template.py hs           # 只跑 hs 管线

约定：
1. 产物是 JS 变量文件（不是 JSON），方便 <script src> 直接加载、零解析成本
2. 每个产物头部必须带：生成时间 + 数据源 + 数据版本（合规与可追溯）
3. 大文件（>1MB）按需拆分章节，避免拖慢首屏（做得比原站更好）
"""

import json
import os
import sys
import datetime

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def write_js(var_name: str, payload, source: str, version: str) -> str:
    """把 Python 数据写成带头注释的 JS 变量文件，返回文件路径"""
    os.makedirs(DATA_DIR, exist_ok=True)
    path = os.path.join(DATA_DIR, f"{var_name}.js")
    stamp = datetime.date.today().isoformat()
    header = (
        f"// Auto-generated by etl_template.py on {stamp}\n"
        f"// Source: {source}\n"
        f"// Data version: {version}\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(f"var {var_name} = ")
        f.write(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    size_kb = os.path.getsize(path) / 1024
    print(f"  [ok] {path} ({size_kb:.1f} KB)")
    return path


# ============================================================
# 管线示例 1：汇率（接 frankfurter.dev 免费API，可离线缓存一份兜底）
# 前端也可直连该API，此管线用于生成兜底快照
# ============================================================
def etl_forex():
    import urllib.request

    print("[forex] 拉取 frankfurter.dev 免费汇率 ...")
    try:
        req = urllib.request.Request(
            "https://api.frankfurter.dev/v1/latest?base=CNY&symbols=USD,EUR,JPY,GBP,HKD",
            headers={"User-Agent": "LogiKit-ETL/0.1"},
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.loads(r.read().decode())
        write_js(
            "FOREX_SNAPSHOT",
            {"date": data["date"], "base": data["base"], "rates": data["rates"]},
            source="https://frankfurter.dev (European Central Bank reference rates)",
            version=data["date"],
        )
    except Exception as e:
        print(f"  [warn] forex 拉取失败（离线开发时正常）: {e}")


# ============================================================
# 管线示例 2：HS 编码（占位骨架）
# 数据源候选：
#   - 海关总署《进出口税则》公开数据（HS 2026，10位本国子目）
#   - 中国出口退税率文库（税务总局/商务部公开）
#   - WTO Tariff Download Facility（各国 6 位 HS 税率，免费）
# 抓取/解析逻辑到位后替换 SAMPLE_DATA
# ============================================================
def etl_hs():
    print("[hs] 生成 HS 编码骨架（占位示例数据）...")
    sample = [
        {"code": "8471.30", "desc": "便携式自动数据处理设备（重量≤10kg）", "unit": "台"},
        {"code": "8507.60", "desc": "锂离子蓄电池", "unit": "个/千克"},
    ]
    write_js(
        "HS_CN",
        {"version": "2026-example", "items": sample},
        source="占位示例 — 正式版接海关总署《进出口税则》",
        version="0.1-example",
    )


# ============================================================
# 管线注册表：新增管线在此登记即可
# ============================================================
PIPELINES = {
    "forex": etl_forex,
    "hs": etl_hs,
}


def main():
    targets = sys.argv[1:] or list(PIPELINES)
    for name in targets:
        if name not in PIPELINES:
            print(f"[skip] 未知管线: {name}")
            continue
        PIPELINES[name]()
    print("\n完成。git add data/ && git commit 即完成数据更新部署。")


if __name__ == "__main__":
    main()
