#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ETL: 欧洲央行参考汇率 -> ZX-LogKit 静态快照
============================================
数据源（与 OneCargoKit 同一公开接口，无需密钥）：
    https://api.frankfurter.dev/v1/latest  (底层为 ECB 每日参考汇率)

模式说明（复刻 OneCargoKit 的"离线优先"做法）：
    ETL 把当天汇率烘焙成静态 data/FOREX_SNAPSHOT.js
    -> 页面断网也能算；联网时可点「刷新」去拉实时值

用法：
    python3 etl/etl_forex.py            # 拉取并更新快照
    python3 etl/etl_forex.py --offline   # 断网时保留上一次快照不动
"""
import json
import os
import sys
import urllib.request
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_FILE = os.path.join(ROOT, "data", "FOREX_SNAPSHOT.js")

API = "https://api.frankfurter.dev/v1/latest?base=EUR"
TIMEOUT = 15
HEADERS = {"User-Agent": "ZX-LogKit-ETL/1.0 (+static site generator)", "Accept": "application/json"}

# 物流业务常用币种中文名（用于页面展示，不属于汇率数据本身）
CN_NAMES = {
    "CNY": "人民币", "USD": "美元", "EUR": "欧元", "JPY": "日元", "GBP": "英镑",
    "HKD": "港币", "KRW": "韩元", "SGD": "新加坡元", "THB": "泰铢", "MYR": "马来西亚林吉特",
    "IDR": "印尼盾", "PHP": "菲律宾比索", "INR": "印度卢比", "AUD": "澳元",
    "NZD": "新西兰元", "CAD": "加元", "CHF": "瑞士法郎", "SEK": "瑞典克朗",
    "NOK": "挪威克朗", "DKK": "丹麦克朗", "PLN": "波兰兹罗提", "TRY": "土耳其里拉",
    "ILS": "以色列新谢克尔", "ZAR": "南非兰特", "BRL": "巴西雷亚尔", "MXN": "墨西哥比索",
    "CZK": "捷克克朗", "HUF": "匈牙利福林", "RON": "罗马尼亚列伊", "ISK": "冰岛克朗",
    "BGN": "保加利亚列弗",
}


def fetch_rates():
    print("拉取: %s" % API)
    req = urllib.request.Request(API, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        raw = json.loads(resp.read().decode("utf-8"))
    rates = dict(raw.get("rates", {}))
    rates[raw.get("base", "EUR")] = 1.0   # 补齐基准币，便于任意两币交叉换算
    return raw.get("date", ""), rates


def main():
    offline = "--offline" in sys.argv
    date, rates = "", {}
    source_note = ""

    if not offline:
        try:
            date, rates = fetch_rates()
            source_note = "https://api.frankfurter.dev (ECB)"
            print("  拿到 %d 个币种，日期 %s" % (len(rates), date))
        except Exception as e:
            print("  ! 拉取失败：%s" % e)

    if not rates:
        # 回退：沿用上一版快照，保证 ETL 断网也不破坏已有数据
        if os.path.exists(OUT_FILE):
            print("  沿用上一次快照，未覆盖")
            return 0
        print("  无网络且无历史快照，放弃")
        return 1

    codes = sorted(rates.keys())
    payload = {
        "meta": {
            "source": source_note,
            "source_url": "https://api.frankfurter.dev/v1/latest",
            "source_detail": "European Central Bank 每日参考汇率",
            "date": date,
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "count": len(codes),
        },
        "names": {c: CN_NAMES.get(c, c) for c in codes},
        "codes": codes,
        "rates": rates,   # 全部以 EUR 为基准，任意交叉汇率由页面按 EUR 中转计算
    }

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by etl/etl_forex.py on %s\n" % payload["meta"]["generated_at"])
        f.write("// Source: %s (%s)\n" % (source_note, payload["meta"]["source_detail"]))
        f.write("// Rate date: %s / %d currencies. DO NOT EDIT MANUALLY.\n" % (date, len(codes)))
        f.write("var FOREX_SNAPSHOT = %s;\n" % body)

    print("已生成: %s (%.1f KB, %d 币种, 汇率日期 %s)"
          % (OUT_FILE, os.path.getsize(OUT_FILE) / 1024, len(codes), date))
    return 0


if __name__ == "__main__":
    sys.exit(main())
