#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ETL: 日本 2026 版进口关税表 -> ZX-LogKit 静态数据文件
=====================================================
数据来源（原始，非第三方转包）：
    日本海关关税表 https://www.customs.go.jp/english/tariff/2026_04_01/index.htm
    抓取自大项目 japan-export-hs/data/japan_tariff_2026_cn.json（5611 条，含中文品名）

设计原则（复刻 OneCargoKit 的"静态数据 + 官方深链接"模式）：
    1. ETL 产出 data/JP_TARIFF.js 静态文件 -> 页面直接 <script> 加载，断网可用
    2. 每行都携带日本海关官网 URL -> 数据存疑时一键跳官方原表核对
    3. 税率列清洗：无法识别为税率的脏数据标记为"需查原表"，绝不猜数

用法：
    python3 etl/etl_jp_tariff.py [--source /path/to/japan_tariff_2026_cn.json]
"""
import json
import os
import re
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

DEFAULT_SOURCE = os.path.join(
    os.path.dirname(ROOT), "japan-export-hs", "data", "japan_tariff_2026_cn.json"
)
OUT_FILE = os.path.join(ROOT, "data", "JP_TARIFF.js")

# 能识别为"税率"的模式：Free / 4.6% / 10% 等
RATE_RE = re.compile(r'^\s*(Free|[0-9]+(\.[0-9]+)?%)\s*$', re.I)


def pick_source():
    if "--source" in sys.argv:
        return sys.argv[sys.argv.index("--source") + 1]
    for cand in [DEFAULT_SOURCE, "japan_tariff_2026_cn.json"]:
        if os.path.exists(cand):
            return cand
    return DEFAULT_SOURCE


def clean_rate(raw):
    """把原始税率列收敛为两类：可识别税率 / None（需查原表）"""
    if raw is None:
        return None
    s = str(raw).strip()
    if not s or s.upper() in ("N/A", "NA", "-", "无数据"):
        return None
    if RATE_RE.match(s):
        return s
    return None  # 脏数据（错位抓取的金额/条文），不猜


def main():
    src = pick_source()
    if not os.path.exists(src):
        print("找不到源数据文件: %s" % src)
        print("用 --source 指定 japan_tariff_2026_cn.json 的路径")
        return 1

    print("读取源数据: %s" % src)
    with open(src, encoding="utf-8") as f:
        d = json.load(f)

    meta = d.get("meta", {})
    rows = d.get("data", [])
    chapters = d.get("chapters", {})
    total = len(rows)
    print("  原始记录: %d 条 / %d 个章" % (total, len(chapters)))

    # 官网目录版本，如 2026_04_01
    m = re.search(r"/tariff/([^/]+)/", meta.get("url", ""))
    version_dir = m.group(1) if m else "2026_04_01"

    clean = 0
    dirty = 0
    out_rows = []
    for r in rows:
        general = clean_rate(r.get("general"))
        wto = clean_rate(r.get("wto"))
        if general is None and (r.get("general") or "").strip() not in ("", "N/A", "无数据"):
            dirty += 1
        if general is not None or wto is not None:
            clean += 1
        out_rows.append([
            r.get("hs", ""),                                     # 0 HS 9位
            r.get("hs_display", r.get("hs", "")),                # 1 展示用 HS
            (r.get("desc_cn") or r.get("desc") or "").strip(),   # 2 中文品名
            (r.get("desc") or "").strip(),                       # 3 英文原商品名
            general or "",                                       # 4 一般税率
            wto or "",                                           # 5 WTO 协定税率
            (r.get("general") or "").strip(),                    # 6 原始 general（脏数据溯源）
            r.get("chapter", 0),                                 # 7 章号
            r.get("heading", ""),                                # 8 品目
        ])

    payload = {
        "meta": {
            "source": "日本海关 customs.go.jp 进口关税表",
            "source_url": "https://www.customs.go.jp/english/tariff/%s/index.htm" % version_dir,
            "version": meta.get("version", "2026.04.01"),
            "version_dir": version_dir,
            "total": total,
            "chapters": len(chapters),
            "has_cn_desc": meta.get("translated_count", 0),
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "clean_rate_rows": clean,
            "unparsed_rate_rows": dirty,
        },
        "chapters": {str(k): v for k, v in chapters.items()},
        "rows": out_rows,
    }

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by etl/etl_jp_tariff.py on %s\n" % payload["meta"]["generated_at"])
        f.write("// Source: %s\n" % payload["meta"]["source_url"])
        f.write("// Records: %d rows / %d chapters. DO NOT EDIT MANUALLY.\n" % (total, len(chapters)))
        f.write("var JP_TARIFF = %s;\n" % body)

    size = os.path.getsize(OUT_FILE)
    print("已生成: %s" % OUT_FILE)
    print("  文件大小: %.2f MB" % (size / 1024 / 1024))
    print("  可识别税率行: %d / 税率列异常需查原表: %d" % (clean, dirty))
    return 0


if __name__ == "__main__":
    sys.exit(main())
